### ISSUE TITLE
No works on Windows 10

### ISSUE THREAD

**Issue by SalvaLQ** [cinnamonkale/chrome-trello-link-opener#1]
I have installed the desktop version of Trello on Windows 10 through the Microsoft app store.
I have installed the extension in Chorme and it doesn't work. The page is blank and the trello app does not open.

**Comment by cinnamonKale** [comment]
hey @codealle, I don't have a computer running Windows so it's not something I can test.

But, I found these two links that show it may not currently be possible for Windows 10:

https://community.atlassian.com/t5/Trello-questions/Can-you-Guys-add-Application-URIs-to-The-Trello-App-for-Windows/qaq-p/1748857

https://community.atlassian.com/t5/Trello-questions/Forcing-Trello-URLs-to-Default-to-Desktop-App/qaq-p/643869

This extension just switches out the URL protocol from `https` to `trello`, so if it is possible for Windows but needs an additional step, feel free to submit a PR!
